services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devPass123
      - POSTGRES_DB=trussdb
    restart: always

volumes:
  db: